jobs:
  - job_id: "batch-demo-1"
    batch_size: 256
    model_name: "dummy-model1"
    input_csv: "input-data/reviews_batch_001.csv"
    output_bucket: "ml-outputs"

  - job_id: "batch-demo-2"
    batch_size: 128
    model_name: "dummy-model2"
    input_csv: "input-data/images_batch_002.csv"
    output_bucket: "ml-outputs"

  - job_id: "batch-demo-3"
    batch_size: 64
    model_name: "dummy-model3"
    input_csv: "input-data/articles_batch_003.csv"
    output_bucket: "ml-outputs"
